### ISSUE TITLE
Add data validation for the incoming data

### ISSUE THREAD

**Issue by mhmdsami** [mhmdsami/pet-store-api#1]
At the moment POST /api/pets accepts any form of incoming data, validating the data before adding it to the database would be good.

**Comment by beheradibas** [comment]
Hi @mhmdsami 

I can see four types of data:
pet_name: this also has to be alphabetical
owner_name: This can be alphabetical
type : can  you suggest a list or I can just validate if the name is alphabetical with spaces
gender: I wish to verify it male or female

If you want any other type of validation do mention the same, or I will try to implement this. 
Assign me the issue if this would be sufficient 😄

**Comment by mhmdsami** [comment]
Hello @beheradibas!
`type` can be a string as well! and How are you planning on implementing this?

**Comment by beheradibas** [comment]
Inside the method implement post I will try to validate the data using helper functions in the same file, and for those not correct I would like to respond with an error message with proper status code, can you suggest on what should I write in that part ?

And that would validate the data before making a post request.

Also we can make the validation functions in separate file reusable in future , but I would like to know do you wish to do so ?

**Comment by mhmdsami** [comment]
Either way is fine with me!, Are planning on using any external libraries?

**Comment by mhmdsami** [comment]
@beheradibas any updates? if you don't want to work on this, I'll assign this to someone else

**Comment by beheradibas** [comment]
I would try to finish this by 10pm today IST. After that feel free to assign it to someone else 😃

**Comment by meltedhyperion** [comment]
I want to work on this issue. Can you assign this to me.

**Comment by mhmdsami** [comment]
completed with #4
