### ISSUE TITLE
fix: 401 error messages

### ISSUE THREAD

**Issue by mhmdsami** [mhmdsami/pet-store-api#2]
https://github.com/mhmdsami/pet-store-api/blob/291cff4fdc65f8c5881eef9f0e82bda72509d88a/src/api/pets.ts#L39

The error message is `You are unauthorized make request` instead of `You are unauthorized to make this request` in several request.

**Comment by SubhamChoudhury** [comment]
Hey @mhmdsami , can I take this up?

**Comment by mhmdsami** [comment]
fixed witth #3
